import { createGlobalTheme } from "@vanilla-extract/css";
import { defineProperties, createSprinkles } from "@vanilla-extract/sprinkles";

export const vars = createGlobalTheme(":root", {
  color: {
    black: "#000",
    nearBlack: "#111",
    darkGray: "#333",
    midGray: "#555",
    gray: "#777",
    silver: "#999",
    lightSilver: "#aaa",
    moonGray: "#ccc",
    lightGray: "#eee",
    nearWhite: "#f4f4f4",
    white: "#fff",
    transparent: "transparent",
    darkRed: "#e7040f",
    red: "#ff4136",
    lightRed: "#ff725c",
    orange: "#ff6300",
    gold: "#ffb700",
    yellow: "#ffd700",
    lightYellow: "#fbf1a9",
    purple: "#5e2ca5",
    lightPurple: "#a463f2",
    darkPink: "#d5008f",
    hotPink: "#ff41b4",
    pink: "#ff80cc",
    lightPink: "#ffa3d7",
    darkGreen: "#137752",
    green: "#19a974",
    lightGreen: "#9eebcf",
    navy: "#001b44",
    darkBlue: "#00449e",
    blue: "#357edd",
    lightBlue: "#96ccff",
    lightestBlue: "#cdecff",
    washedBlue: "#f6fffe",
    washedGreen: "#e8fdf5",
    washedYellow: "#fffceb",
    washedRed: "#ffdfdf",
    washedGray: "#f6f6f6",
    highlight: "#ffff00",
  },
  font: {
    body: "arial",
  },
  fontSize: {
    p: "16px",
    h1: "32px",
    h2: "24px",
    h3: "20px",
    h4: "16px",
    h5: "14px",
    h6: "12px",
    small: "12px",
  },
  fontWeight: {
    "400": "400",
    "600": "600",
  },
  space: {
    0: "0",
    4: "4px",
    8: "8px",
    12: "12px",
    16: "16px",
    24: "24px",
    32: "32px",
    48: "48px",
    64: "64px",
    96: "96px",
    128: "128px",
    256: "256px",
  },
});

const layoutStyles = defineProperties({
  conditions: {
    default: {},
    mobile: {},
    tablet: { "@media": "screen and (min-width: 768px)" },
    desktop: { "@media": "screen and (min-width: 1024px)" },
    hover: { selector: "&:hover" },
    focus: { selector: "&:focus" },
    active: { selector: "&:active" },
  },
  defaultCondition: "default",
  properties: {
    display: ["none", "block", "flex"],
    flexDirection: ["row", "column"],
    paddingTop: vars.space,
    paddingBottom: vars.space,
    paddingLeft: vars.space,
    paddingRight: vars.space,
    margin: vars.space,
    width: ["16px", "100%", "auto", "fit-content"],
    fontSize: vars.fontSize,
    fontWeight: vars.fontWeight,
    fontFamily: vars.font,
    borderRadius: vars.space,
    border: ["none", "2px solid", "4px solid", "8px solid"],
    borderColor: vars.color,
    outline: ["none", "2px solid", "4px solid", "8px solid"],
    outlineColor: vars.color,
    color: vars.color,
    background: vars.color,
    textDecoration: ["none", "underline"],
    // etc.
  },
  shorthands: {
    padding: ["paddingTop", "paddingBottom", "paddingLeft", "paddingRight"],
    paddingX: ["paddingLeft", "paddingRight"],
    paddingY: ["paddingTop", "paddingBottom"],
  },
});

export const atoms = createSprinkles(layoutStyles);
